# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sam-o-reilly/AsteroidDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sam-o-reilly/AsteroidDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam-o-reilly/AsteroidDB/CMakeFiles /home/sam-o-reilly/AsteroidDB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam-o-reilly/AsteroidDB/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam-o-reilly/AsteroidDB/CMakeFiles /home/sam-o-reilly/AsteroidDB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sam-o-reilly/AsteroidDB/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AsteroidDB

# Build rule for target.
AsteroidDB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AsteroidDB
.PHONY : AsteroidDB

# fast build rule for target.
AsteroidDB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/build
.PHONY : AsteroidDB/fast

core/main.o: core/main.cpp.o
.PHONY : core/main.o

# target to build an object file
core/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/main.cpp.o
.PHONY : core/main.cpp.o

core/main.i: core/main.cpp.i
.PHONY : core/main.i

# target to preprocess a source file
core/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/main.cpp.i
.PHONY : core/main.cpp.i

core/main.s: core/main.cpp.s
.PHONY : core/main.s

# target to generate assembly for a file
core/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/main.cpp.s
.PHONY : core/main.cpp.s

core/sql/ast/Node.o: core/sql/ast/Node.cpp.o
.PHONY : core/sql/ast/Node.o

# target to build an object file
core/sql/ast/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/ast/Node.cpp.o
.PHONY : core/sql/ast/Node.cpp.o

core/sql/ast/Node.i: core/sql/ast/Node.cpp.i
.PHONY : core/sql/ast/Node.i

# target to preprocess a source file
core/sql/ast/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/ast/Node.cpp.i
.PHONY : core/sql/ast/Node.cpp.i

core/sql/ast/Node.s: core/sql/ast/Node.cpp.s
.PHONY : core/sql/ast/Node.s

# target to generate assembly for a file
core/sql/ast/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/ast/Node.cpp.s
.PHONY : core/sql/ast/Node.cpp.s

core/sql/ast/Parser.o: core/sql/ast/Parser.cpp.o
.PHONY : core/sql/ast/Parser.o

# target to build an object file
core/sql/ast/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/ast/Parser.cpp.o
.PHONY : core/sql/ast/Parser.cpp.o

core/sql/ast/Parser.i: core/sql/ast/Parser.cpp.i
.PHONY : core/sql/ast/Parser.i

# target to preprocess a source file
core/sql/ast/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/ast/Parser.cpp.i
.PHONY : core/sql/ast/Parser.cpp.i

core/sql/ast/Parser.s: core/sql/ast/Parser.cpp.s
.PHONY : core/sql/ast/Parser.s

# target to generate assembly for a file
core/sql/ast/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/ast/Parser.cpp.s
.PHONY : core/sql/ast/Parser.cpp.s

core/sql/lexer/lexer.o: core/sql/lexer/lexer.cpp.o
.PHONY : core/sql/lexer/lexer.o

# target to build an object file
core/sql/lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/lexer/lexer.cpp.o
.PHONY : core/sql/lexer/lexer.cpp.o

core/sql/lexer/lexer.i: core/sql/lexer/lexer.cpp.i
.PHONY : core/sql/lexer/lexer.i

# target to preprocess a source file
core/sql/lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/lexer/lexer.cpp.i
.PHONY : core/sql/lexer/lexer.cpp.i

core/sql/lexer/lexer.s: core/sql/lexer/lexer.cpp.s
.PHONY : core/sql/lexer/lexer.s

# target to generate assembly for a file
core/sql/lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/lexer/lexer.cpp.s
.PHONY : core/sql/lexer/lexer.cpp.s

core/sql/parser/Create.o: core/sql/parser/Create.cpp.o
.PHONY : core/sql/parser/Create.o

# target to build an object file
core/sql/parser/Create.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Create.cpp.o
.PHONY : core/sql/parser/Create.cpp.o

core/sql/parser/Create.i: core/sql/parser/Create.cpp.i
.PHONY : core/sql/parser/Create.i

# target to preprocess a source file
core/sql/parser/Create.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Create.cpp.i
.PHONY : core/sql/parser/Create.cpp.i

core/sql/parser/Create.s: core/sql/parser/Create.cpp.s
.PHONY : core/sql/parser/Create.s

# target to generate assembly for a file
core/sql/parser/Create.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Create.cpp.s
.PHONY : core/sql/parser/Create.cpp.s

core/sql/parser/Insert.o: core/sql/parser/Insert.cpp.o
.PHONY : core/sql/parser/Insert.o

# target to build an object file
core/sql/parser/Insert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Insert.cpp.o
.PHONY : core/sql/parser/Insert.cpp.o

core/sql/parser/Insert.i: core/sql/parser/Insert.cpp.i
.PHONY : core/sql/parser/Insert.i

# target to preprocess a source file
core/sql/parser/Insert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Insert.cpp.i
.PHONY : core/sql/parser/Insert.cpp.i

core/sql/parser/Insert.s: core/sql/parser/Insert.cpp.s
.PHONY : core/sql/parser/Insert.s

# target to generate assembly for a file
core/sql/parser/Insert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Insert.cpp.s
.PHONY : core/sql/parser/Insert.cpp.s

core/sql/parser/Select.o: core/sql/parser/Select.cpp.o
.PHONY : core/sql/parser/Select.o

# target to build an object file
core/sql/parser/Select.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Select.cpp.o
.PHONY : core/sql/parser/Select.cpp.o

core/sql/parser/Select.i: core/sql/parser/Select.cpp.i
.PHONY : core/sql/parser/Select.i

# target to preprocess a source file
core/sql/parser/Select.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Select.cpp.i
.PHONY : core/sql/parser/Select.cpp.i

core/sql/parser/Select.s: core/sql/parser/Select.cpp.s
.PHONY : core/sql/parser/Select.s

# target to generate assembly for a file
core/sql/parser/Select.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AsteroidDB.dir/build.make CMakeFiles/AsteroidDB.dir/core/sql/parser/Select.cpp.s
.PHONY : core/sql/parser/Select.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AsteroidDB"
	@echo "... core/main.o"
	@echo "... core/main.i"
	@echo "... core/main.s"
	@echo "... core/sql/ast/Node.o"
	@echo "... core/sql/ast/Node.i"
	@echo "... core/sql/ast/Node.s"
	@echo "... core/sql/ast/Parser.o"
	@echo "... core/sql/ast/Parser.i"
	@echo "... core/sql/ast/Parser.s"
	@echo "... core/sql/lexer/lexer.o"
	@echo "... core/sql/lexer/lexer.i"
	@echo "... core/sql/lexer/lexer.s"
	@echo "... core/sql/parser/Create.o"
	@echo "... core/sql/parser/Create.i"
	@echo "... core/sql/parser/Create.s"
	@echo "... core/sql/parser/Insert.o"
	@echo "... core/sql/parser/Insert.i"
	@echo "... core/sql/parser/Insert.s"
	@echo "... core/sql/parser/Select.o"
	@echo "... core/sql/parser/Select.i"
	@echo "... core/sql/parser/Select.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

